# Generated by Django 6.0.1 on 2026-02-28 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='amount',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='listing',
            name='starting_bid',
            field=models.CharField(),
        ),
    ]
